
// MIT License
// 
// Copyright (c) 2009-2017 Luca Piccioni
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
// 
// This file is automatically generated

#pragma warning disable 649, 1572, 1573

// ReSharper disable RedundantUsingDirective
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;
using System.Security;
using System.Text;

using Khronos;

// ReSharper disable CheckNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable JoinDeclarationAndInitializer

namespace OpenGL
{
	public partial class Gl
	{
		/// <summary>
		/// [GL] Value of GL_SRGB_DECODE_ARB symbol.
		/// </summary>
		[RequiredByFeature("GL_ARB_internalformat_query2", Api = "gl|glcore")]
		public const int SRGB_DECODE_ARB = 0x8299;

		/// <summary>
		/// [GL] Value of GL_VIEW_CLASS_EAC_R11 symbol.
		/// </summary>
		[RequiredByFeature("GL_ARB_internalformat_query2", Api = "gl|glcore")]
		public const int VIEW_CLASS_EAC_R11 = 0x9383;

		/// <summary>
		/// [GL] Value of GL_VIEW_CLASS_EAC_RG11 symbol.
		/// </summary>
		[RequiredByFeature("GL_ARB_internalformat_query2", Api = "gl|glcore")]
		public const int VIEW_CLASS_EAC_RG11 = 0x9384;

		/// <summary>
		/// [GL] Value of GL_VIEW_CLASS_ETC2_RGB symbol.
		/// </summary>
		[RequiredByFeature("GL_ARB_internalformat_query2", Api = "gl|glcore")]
		public const int VIEW_CLASS_ETC2_RGB = 0x9385;

		/// <summary>
		/// [GL] Value of GL_VIEW_CLASS_ETC2_RGBA symbol.
		/// </summary>
		[RequiredByFeature("GL_ARB_internalformat_query2", Api = "gl|glcore")]
		public const int VIEW_CLASS_ETC2_RGBA = 0x9386;

		/// <summary>
		/// [GL] Value of GL_VIEW_CLASS_ETC2_EAC_RGBA symbol.
		/// </summary>
		[RequiredByFeature("GL_ARB_internalformat_query2", Api = "gl|glcore")]
		public const int VIEW_CLASS_ETC2_EAC_RGBA = 0x9387;

		/// <summary>
		/// [GL] Value of GL_VIEW_CLASS_ASTC_4x4_RGBA symbol.
		/// </summary>
		[RequiredByFeature("GL_ARB_internalformat_query2", Api = "gl|glcore")]
		public const int VIEW_CLASS_ASTC_4x4_RGBA = 0x9388;

		/// <summary>
		/// [GL] Value of GL_VIEW_CLASS_ASTC_5x4_RGBA symbol.
		/// </summary>
		[RequiredByFeature("GL_ARB_internalformat_query2", Api = "gl|glcore")]
		public const int VIEW_CLASS_ASTC_5x4_RGBA = 0x9389;

		/// <summary>
		/// [GL] Value of GL_VIEW_CLASS_ASTC_5x5_RGBA symbol.
		/// </summary>
		[RequiredByFeature("GL_ARB_internalformat_query2", Api = "gl|glcore")]
		public const int VIEW_CLASS_ASTC_5x5_RGBA = 0x938A;

		/// <summary>
		/// [GL] Value of GL_VIEW_CLASS_ASTC_6x5_RGBA symbol.
		/// </summary>
		[RequiredByFeature("GL_ARB_internalformat_query2", Api = "gl|glcore")]
		public const int VIEW_CLASS_ASTC_6x5_RGBA = 0x938B;

		/// <summary>
		/// [GL] Value of GL_VIEW_CLASS_ASTC_6x6_RGBA symbol.
		/// </summary>
		[RequiredByFeature("GL_ARB_internalformat_query2", Api = "gl|glcore")]
		public const int VIEW_CLASS_ASTC_6x6_RGBA = 0x938C;

		/// <summary>
		/// [GL] Value of GL_VIEW_CLASS_ASTC_8x5_RGBA symbol.
		/// </summary>
		[RequiredByFeature("GL_ARB_internalformat_query2", Api = "gl|glcore")]
		public const int VIEW_CLASS_ASTC_8x5_RGBA = 0x938D;

		/// <summary>
		/// [GL] Value of GL_VIEW_CLASS_ASTC_8x6_RGBA symbol.
		/// </summary>
		[RequiredByFeature("GL_ARB_internalformat_query2", Api = "gl|glcore")]
		public const int VIEW_CLASS_ASTC_8x6_RGBA = 0x938E;

		/// <summary>
		/// [GL] Value of GL_VIEW_CLASS_ASTC_8x8_RGBA symbol.
		/// </summary>
		[RequiredByFeature("GL_ARB_internalformat_query2", Api = "gl|glcore")]
		public const int VIEW_CLASS_ASTC_8x8_RGBA = 0x938F;

		/// <summary>
		/// [GL] Value of GL_VIEW_CLASS_ASTC_10x5_RGBA symbol.
		/// </summary>
		[RequiredByFeature("GL_ARB_internalformat_query2", Api = "gl|glcore")]
		public const int VIEW_CLASS_ASTC_10x5_RGBA = 0x9390;

		/// <summary>
		/// [GL] Value of GL_VIEW_CLASS_ASTC_10x6_RGBA symbol.
		/// </summary>
		[RequiredByFeature("GL_ARB_internalformat_query2", Api = "gl|glcore")]
		public const int VIEW_CLASS_ASTC_10x6_RGBA = 0x9391;

		/// <summary>
		/// [GL] Value of GL_VIEW_CLASS_ASTC_10x8_RGBA symbol.
		/// </summary>
		[RequiredByFeature("GL_ARB_internalformat_query2", Api = "gl|glcore")]
		public const int VIEW_CLASS_ASTC_10x8_RGBA = 0x9392;

		/// <summary>
		/// [GL] Value of GL_VIEW_CLASS_ASTC_10x10_RGBA symbol.
		/// </summary>
		[RequiredByFeature("GL_ARB_internalformat_query2", Api = "gl|glcore")]
		public const int VIEW_CLASS_ASTC_10x10_RGBA = 0x9393;

		/// <summary>
		/// [GL] Value of GL_VIEW_CLASS_ASTC_12x10_RGBA symbol.
		/// </summary>
		[RequiredByFeature("GL_ARB_internalformat_query2", Api = "gl|glcore")]
		public const int VIEW_CLASS_ASTC_12x10_RGBA = 0x9394;

		/// <summary>
		/// [GL] Value of GL_VIEW_CLASS_ASTC_12x12_RGBA symbol.
		/// </summary>
		[RequiredByFeature("GL_ARB_internalformat_query2", Api = "gl|glcore")]
		public const int VIEW_CLASS_ASTC_12x12_RGBA = 0x9395;

	}

}
