
coverage:
  precision: 2
  round: down
  status:
    project: yes
    patch: yes
    changes: yes

ignore:
  - 'BindingsGen/**'
  - 'OpenGL.Net/Egl.Extensions.cs'
  - 'OpenGL.Net/Egl.VERSION*.cs'
  - 'OpenGL.Net/Egl.Versions.cs'
  - 'OpenGL.Net/Gl.Enums.cs'
  - 'OpenGL.Net/Gl.Limits.cs'
  - 'OpenGL.Net/Gl.ES_VERSION*.cs'
  - 'OpenGL.Net/Gl.SC_VERSION*.cs'
  - 'OpenGL.Net/Gl.Vb.cs'
  - 'OpenGL.Net/Gl.VERSION*.cs'
  - 'OpenGL.Net/Gl.Versions.cs'
  - 'OpenGL.Net/Glx.Extensions.cs'
  - 'OpenGL.Net/Glx.VERSION*.cs'
  - 'OpenGL.Net/Glx.Versions.cs'
  - 'OpenGL.Net/Wgl.Extensions.cs'
  - 'OpenGL.Net/Wgl.VERSION*.cs'
  - 'OpenGL.Net/Wgl.Versions.cs'
  - 'OpenGL.Net/3DFX/**'
  - 'OpenGL.Net/3DL/**'
  - 'OpenGL.Net/AMD/**'
  - 'OpenGL.Net/ANDROID/**'
  - 'OpenGL.Net/ANGLE/**'
  - 'OpenGL.Net/APPLE/**'
  - 'OpenGL.Net/ARB/**'
  - 'OpenGL.Net/ARM/**'
  - 'OpenGL.Net/ATI/**'
  - 'OpenGL.Net/DMP/**'
  - 'OpenGL.Net/EXT/**'
  - 'OpenGL.Net/FJ/**'
  - 'OpenGL.Net/GREMEDY/**'
  - 'OpenGL.Net/HI/**'
  - 'OpenGL.Net/HP/**'
  - 'OpenGL.Net/I3D/**'
  - 'OpenGL.Net/IBM/**'
  - 'OpenGL.Net/IMG/**'
  - 'OpenGL.Net/INGR/**'
  - 'OpenGL.Net/INTEL/**'
  - 'OpenGL.Net/KHR/**'
  - 'OpenGL.Net/MESA/**'
  - 'OpenGL.Net/MESAX/**'
  - 'OpenGL.Net/NOK/**'
  - 'OpenGL.Net/NV/**'
  - 'OpenGL.Net/NVX/**'
  - 'OpenGL.Net/OES/**'
  - 'OpenGL.Net/OML/**'
  - 'OpenGL.Net/PGI/**'
  - 'OpenGL.Net/QCOM/**'
  - 'OpenGL.Net/REND/**'
  - 'OpenGL.Net/S3/**'
  - 'OpenGL.Net/SGI/**'
  - 'OpenGL.Net/SGIS/**'
  - 'OpenGL.Net/SGIX/**'
  - 'OpenGL.Net/SUN/**'
  - 'OpenGL.Net/SUNX/**'
  - 'OpenGL.Net/TIZEN/**'
  - 'OpenGL.Net/VIV/**'
  - 'OpenGL.Net/WIN/**'

