
// MIT License
// 
// Copyright (c) 2009-2017 Luca Piccioni
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
// 
// This file is automatically generated

using Khronos;

namespace OpenGL
{
	public partial class Glx
	{
		#region Known Versions Constants

		/// <summary>
		/// Version for GLX_VERSION_1_0 API.
		/// </summary>
		public static readonly KhronosVersion Version_100 = new KhronosVersion(1, 0, KhronosVersion.ApiGlx);

		/// <summary>
		/// Version for GLX_VERSION_1_1 API.
		/// </summary>
		public static readonly KhronosVersion Version_110 = new KhronosVersion(1, 1, KhronosVersion.ApiGlx);

		/// <summary>
		/// Version for GLX_VERSION_1_2 API.
		/// </summary>
		public static readonly KhronosVersion Version_120 = new KhronosVersion(1, 2, KhronosVersion.ApiGlx);

		/// <summary>
		/// Version for GLX_VERSION_1_3 API.
		/// </summary>
		public static readonly KhronosVersion Version_130 = new KhronosVersion(1, 3, KhronosVersion.ApiGlx);

		/// <summary>
		/// Version for GLX_VERSION_1_4 API.
		/// </summary>
		public static readonly KhronosVersion Version_140 = new KhronosVersion(1, 4, KhronosVersion.ApiGlx);

		#endregion

	}

}
