
// MIT License
// 
// Copyright (c) 2009-2017 Luca Piccioni
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
// 
// This file is automatically generated

#pragma warning disable 649, 1572, 1573

// ReSharper disable RedundantUsingDirective
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;
using System.Security;
using System.Text;

using Khronos;

// ReSharper disable CheckNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable JoinDeclarationAndInitializer

namespace OpenGL
{
	public partial class Gl
	{
		/// <summary>
		/// [GL] Value of GL_RED_MIN_CLAMP_INGR symbol.
		/// </summary>
		[RequiredByFeature("GL_INGR_color_clamp")]
		public const int RED_MIN_CLAMP_INGR = 0x8560;

		/// <summary>
		/// [GL] Value of GL_GREEN_MIN_CLAMP_INGR symbol.
		/// </summary>
		[RequiredByFeature("GL_INGR_color_clamp")]
		public const int GREEN_MIN_CLAMP_INGR = 0x8561;

		/// <summary>
		/// [GL] Value of GL_BLUE_MIN_CLAMP_INGR symbol.
		/// </summary>
		[RequiredByFeature("GL_INGR_color_clamp")]
		public const int BLUE_MIN_CLAMP_INGR = 0x8562;

		/// <summary>
		/// [GL] Value of GL_ALPHA_MIN_CLAMP_INGR symbol.
		/// </summary>
		[RequiredByFeature("GL_INGR_color_clamp")]
		public const int ALPHA_MIN_CLAMP_INGR = 0x8563;

		/// <summary>
		/// [GL] Value of GL_RED_MAX_CLAMP_INGR symbol.
		/// </summary>
		[RequiredByFeature("GL_INGR_color_clamp")]
		public const int RED_MAX_CLAMP_INGR = 0x8564;

		/// <summary>
		/// [GL] Value of GL_GREEN_MAX_CLAMP_INGR symbol.
		/// </summary>
		[RequiredByFeature("GL_INGR_color_clamp")]
		public const int GREEN_MAX_CLAMP_INGR = 0x8565;

		/// <summary>
		/// [GL] Value of GL_BLUE_MAX_CLAMP_INGR symbol.
		/// </summary>
		[RequiredByFeature("GL_INGR_color_clamp")]
		public const int BLUE_MAX_CLAMP_INGR = 0x8566;

		/// <summary>
		/// [GL] Value of GL_ALPHA_MAX_CLAMP_INGR symbol.
		/// </summary>
		[RequiredByFeature("GL_INGR_color_clamp")]
		public const int ALPHA_MAX_CLAMP_INGR = 0x8567;

	}

}
