
// MIT License
// 
// Copyright (c) 2009-2017 Luca Piccioni
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
// 
// This file is automatically generated

#pragma warning disable 649, 1572, 1573

// ReSharper disable RedundantUsingDirective
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;
using System.Security;
using System.Text;

using Khronos;

// ReSharper disable CheckNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable JoinDeclarationAndInitializer

namespace OpenGL
{
	public partial class Gl
	{
		/// <summary>
		/// [GL] Value of GL_ARRAY_ELEMENT_LOCK_FIRST_EXT symbol.
		/// </summary>
		[RequiredByFeature("GL_EXT_compiled_vertex_array")]
		public const int ARRAY_ELEMENT_LOCK_FIRST_EXT = 0x81A8;

		/// <summary>
		/// [GL] Value of GL_ARRAY_ELEMENT_LOCK_COUNT_EXT symbol.
		/// </summary>
		[RequiredByFeature("GL_EXT_compiled_vertex_array")]
		public const int ARRAY_ELEMENT_LOCK_COUNT_EXT = 0x81A9;

		/// <summary>
		/// [GL] glLockArraysEXT: Binding for glLockArraysEXT.
		/// </summary>
		/// <param name="first">
		/// A <see cref="T:int"/>.
		/// </param>
		/// <param name="count">
		/// A <see cref="T:int"/>.
		/// </param>
		[RequiredByFeature("GL_EXT_compiled_vertex_array")]
		public static void LockArraysEXT(int first, int count)
		{
			Debug.Assert(Delegates.pglLockArraysEXT != null, "pglLockArraysEXT not implemented");
			Delegates.pglLockArraysEXT(first, count);
			LogCommand("glLockArraysEXT", null, first, count			);
			DebugCheckErrors(null);
		}

		/// <summary>
		/// [GL] glUnlockArraysEXT: Binding for glUnlockArraysEXT.
		/// </summary>
		[RequiredByFeature("GL_EXT_compiled_vertex_array")]
		public static void UnlockArraysEXT()
		{
			Debug.Assert(Delegates.pglUnlockArraysEXT != null, "pglUnlockArraysEXT not implemented");
			Delegates.pglUnlockArraysEXT();
			LogCommand("glUnlockArraysEXT", null			);
			DebugCheckErrors(null);
		}

		internal static unsafe partial class Delegates
		{
			[RequiredByFeature("GL_EXT_compiled_vertex_array")]
			[SuppressUnmanagedCodeSecurity]
			internal delegate void glLockArraysEXT(int first, int count);

			[RequiredByFeature("GL_EXT_compiled_vertex_array")]
			[ThreadStatic]
			internal static glLockArraysEXT pglLockArraysEXT;

			[RequiredByFeature("GL_EXT_compiled_vertex_array")]
			[SuppressUnmanagedCodeSecurity]
			internal delegate void glUnlockArraysEXT();

			[RequiredByFeature("GL_EXT_compiled_vertex_array")]
			[ThreadStatic]
			internal static glUnlockArraysEXT pglUnlockArraysEXT;

		}
	}

}
