
// MIT License
// 
// Copyright (c) 2009-2017 Luca Piccioni
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
// 
// This file is automatically generated

#pragma warning disable 649, 1572, 1573

// ReSharper disable RedundantUsingDirective
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;
using System.Security;
using System.Text;

using Khronos;

// ReSharper disable CheckNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable JoinDeclarationAndInitializer

namespace OpenGL
{
	public partial class Gl
	{
		/// <summary>
		/// [GL] Value of GL_INDEX_TEST_EXT symbol.
		/// </summary>
		[RequiredByFeature("GL_EXT_index_func")]
		public const int INDEX_TEST_EXT = 0x81B5;

		/// <summary>
		/// [GL] Value of GL_INDEX_TEST_FUNC_EXT symbol.
		/// </summary>
		[RequiredByFeature("GL_EXT_index_func")]
		public const int INDEX_TEST_FUNC_EXT = 0x81B6;

		/// <summary>
		/// [GL] Value of GL_INDEX_TEST_REF_EXT symbol.
		/// </summary>
		[RequiredByFeature("GL_EXT_index_func")]
		public const int INDEX_TEST_REF_EXT = 0x81B7;

		/// <summary>
		/// [GL] glIndexFuncEXT: Binding for glIndexFuncEXT.
		/// </summary>
		/// <param name="func">
		/// A <see cref="T:int"/>.
		/// </param>
		/// <param name="ref">
		/// A <see cref="T:float"/>.
		/// </param>
		[RequiredByFeature("GL_EXT_index_func")]
		public static void IndexFuncEXT(int func, float @ref)
		{
			Debug.Assert(Delegates.pglIndexFuncEXT != null, "pglIndexFuncEXT not implemented");
			Delegates.pglIndexFuncEXT(func, @ref);
			LogCommand("glIndexFuncEXT", null, func, @ref			);
			DebugCheckErrors(null);
		}

		internal static unsafe partial class Delegates
		{
			[RequiredByFeature("GL_EXT_index_func")]
			[SuppressUnmanagedCodeSecurity]
			internal delegate void glIndexFuncEXT(int func, float @ref);

			[RequiredByFeature("GL_EXT_index_func")]
			[ThreadStatic]
			internal static glIndexFuncEXT pglIndexFuncEXT;

		}
	}

}
