
// MIT License
// 
// Copyright (c) 2009-2017 Luca Piccioni
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
// 
// This file is automatically generated

#pragma warning disable 649, 1572, 1573

// ReSharper disable RedundantUsingDirective
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;
using System.Security;
using System.Text;

using Khronos;

// ReSharper disable CheckNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable JoinDeclarationAndInitializer

namespace OpenGL
{
	public partial class Gl
	{
		/// <summary>
		/// [GL] Value of GL_PIXEL_TEX_GEN_SGIX symbol.
		/// </summary>
		[RequiredByFeature("GL_SGIX_pixel_texture")]
		public const int PIXEL_TEX_GEN_SGIX = 0x8139;

		/// <summary>
		/// [GL] Value of GL_PIXEL_TEX_GEN_MODE_SGIX symbol.
		/// </summary>
		[RequiredByFeature("GL_SGIX_pixel_texture")]
		public const int PIXEL_TEX_GEN_MODE_SGIX = 0x832B;

		/// <summary>
		/// [GL] glPixelTexGenSGIX: Binding for glPixelTexGenSGIX.
		/// </summary>
		/// <param name="mode">
		/// A <see cref="T:int"/>.
		/// </param>
		[RequiredByFeature("GL_SGIX_pixel_texture")]
		public static void PixelTexGenSGIX(int mode)
		{
			Debug.Assert(Delegates.pglPixelTexGenSGIX != null, "pglPixelTexGenSGIX not implemented");
			Delegates.pglPixelTexGenSGIX(mode);
			LogCommand("glPixelTexGenSGIX", null, mode			);
			DebugCheckErrors(null);
		}

		internal static unsafe partial class Delegates
		{
			[RequiredByFeature("GL_SGIX_pixel_texture")]
			[SuppressUnmanagedCodeSecurity]
			internal delegate void glPixelTexGenSGIX(int mode);

			[RequiredByFeature("GL_SGIX_pixel_texture")]
			[ThreadStatic]
			internal static glPixelTexGenSGIX pglPixelTexGenSGIX;

		}
	}

}
