
// MIT License
// 
// Copyright (c) 2009-2017 Luca Piccioni
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
// 
// This file is automatically generated

#pragma warning disable 649, 1572, 1573

// ReSharper disable RedundantUsingDirective
using System;
using System.Diagnostics;
using System.Runtime.InteropServices;
using System.Security;
using System.Text;

using Khronos;

// ReSharper disable CheckNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable JoinDeclarationAndInitializer

namespace OpenGL
{
	public partial class Gl
	{
		/// <summary>
		/// [GL] Value of GL_SUBGROUP_SIZE_KHR symbol.
		/// </summary>
		[RequiredByFeature("GL_KHR_shader_subgroup", Api = "gl|glcore|gles2")]
		public const int SUBGROUP_SIZE_KHR = 0x9532;

		/// <summary>
		/// [GL] Value of GL_SUBGROUP_SUPPORTED_STAGES_KHR symbol.
		/// </summary>
		[RequiredByFeature("GL_KHR_shader_subgroup", Api = "gl|glcore|gles2")]
		public const int SUBGROUP_SUPPORTED_STAGES_KHR = 0x9533;

		/// <summary>
		/// [GL] Value of GL_SUBGROUP_SUPPORTED_FEATURES_KHR symbol.
		/// </summary>
		[RequiredByFeature("GL_KHR_shader_subgroup", Api = "gl|glcore|gles2")]
		public const int SUBGROUP_SUPPORTED_FEATURES_KHR = 0x9534;

		/// <summary>
		/// [GL] Value of GL_SUBGROUP_QUAD_ALL_STAGES_KHR symbol.
		/// </summary>
		[RequiredByFeature("GL_KHR_shader_subgroup", Api = "gl|glcore|gles2")]
		public const int SUBGROUP_QUAD_ALL_STAGES_KHR = 0x9535;

		/// <summary>
		/// [GL] Value of GL_SUBGROUP_FEATURE_BASIC_BIT_KHR symbol.
		/// </summary>
		[RequiredByFeature("GL_KHR_shader_subgroup", Api = "gl|glcore|gles2")]
		[Log(BitmaskName = "GL")]
		public const uint SUBGROUP_FEATURE_BASIC_BIT_KHR = 0x00000001;

		/// <summary>
		/// [GL] Value of GL_SUBGROUP_FEATURE_VOTE_BIT_KHR symbol.
		/// </summary>
		[RequiredByFeature("GL_KHR_shader_subgroup", Api = "gl|glcore|gles2")]
		[Log(BitmaskName = "GL")]
		public const uint SUBGROUP_FEATURE_VOTE_BIT_KHR = 0x00000002;

		/// <summary>
		/// [GL] Value of GL_SUBGROUP_FEATURE_ARITHMETIC_BIT_KHR symbol.
		/// </summary>
		[RequiredByFeature("GL_KHR_shader_subgroup", Api = "gl|glcore|gles2")]
		[Log(BitmaskName = "GL")]
		public const uint SUBGROUP_FEATURE_ARITHMETIC_BIT_KHR = 0x00000004;

		/// <summary>
		/// [GL] Value of GL_SUBGROUP_FEATURE_BALLOT_BIT_KHR symbol.
		/// </summary>
		[RequiredByFeature("GL_KHR_shader_subgroup", Api = "gl|glcore|gles2")]
		[Log(BitmaskName = "GL")]
		public const uint SUBGROUP_FEATURE_BALLOT_BIT_KHR = 0x00000008;

		/// <summary>
		/// [GL] Value of GL_SUBGROUP_FEATURE_SHUFFLE_BIT_KHR symbol.
		/// </summary>
		[RequiredByFeature("GL_KHR_shader_subgroup", Api = "gl|glcore|gles2")]
		[Log(BitmaskName = "GL")]
		public const uint SUBGROUP_FEATURE_SHUFFLE_BIT_KHR = 0x00000010;

		/// <summary>
		/// [GL] Value of GL_SUBGROUP_FEATURE_SHUFFLE_RELATIVE_BIT_KHR symbol.
		/// </summary>
		[RequiredByFeature("GL_KHR_shader_subgroup", Api = "gl|glcore|gles2")]
		[Log(BitmaskName = "GL")]
		public const uint SUBGROUP_FEATURE_SHUFFLE_RELATIVE_BIT_KHR = 0x00000020;

		/// <summary>
		/// [GL] Value of GL_SUBGROUP_FEATURE_CLUSTERED_BIT_KHR symbol.
		/// </summary>
		[RequiredByFeature("GL_KHR_shader_subgroup", Api = "gl|glcore|gles2")]
		[Log(BitmaskName = "GL")]
		public const uint SUBGROUP_FEATURE_CLUSTERED_BIT_KHR = 0x00000040;

		/// <summary>
		/// [GL] Value of GL_SUBGROUP_FEATURE_QUAD_BIT_KHR symbol.
		/// </summary>
		[RequiredByFeature("GL_KHR_shader_subgroup", Api = "gl|glcore|gles2")]
		[Log(BitmaskName = "GL")]
		public const uint SUBGROUP_FEATURE_QUAD_BIT_KHR = 0x00000080;

	}

}
